{"name": "test_invalid_credentials[edge]", "status": "passed", "attachments": [{"name": "stdout", "source": "52b794fe-da1b-4e7c-9670-b1bb9082f490-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "initialize_driver", "value": "'edge'"}], "start": 1742851590228, "stop": 1742851591046, "uuid": "48c3c5a0-1c9a-4185-8a67-80a7a1c74df7", "historyId": "db8318adea247d3ded4cf2d59e8d65c7", "testCaseId": "9a79481849733b6c79e56b589f44bc63", "fullName": "QATests.tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('initialize_driver')"}, {"name": "parentSuite", "value": "QATests.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ShawnAcer"}, {"name": "thread", "value": "80872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "QATests.tests.test_login"}]}